In [ ]:
%pip install gymnasium

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 12.1 MB/s eta 0:00:00


In [ ]:
import numpy as np #Scientific calculation or to deal with arrays
import gymnasium as gym #provides you with the environment

In [ ]:
env=gym.make()   #Ctrl + Mouse hover

In [ ]:
env = gym.make('CliffWalking-v0',render_mode='rgb_array')#rgb_array for recording video
n_observations = env.observation_space.n
n_actions = env.action_space.n

In [ ]:
print('Number of States',n_observations)
print('Number of possible actions',n_actions)

Number of States 48
Number of possible actions 4


In [ ]:
#Initialize the Q-table to 0
Q_table = np.zeros((n_observations,n_actions))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
Q_table.shape #48 States with 4 actions each

(48, 4)

In [ ]:
#number of episode we will run
n_episodes = 50000

#maximum of iteration per episode- Or number of steps per episode
steps_allowed = 500

#initialize the exploration probability to 1
epsilon = 1

#exploartion decreasing decay for exponential decreasing
decay_rate = 0.001

# minimum of exploration proba
min_epsilon = 0.01

#max exploration rate
max_epsilon=1

#discounted factor- Return G(t)- continuos task
gamma = 0.97

#learning rate - Alpha - Update Q values- storing new info as well as preserving the old one
lr = 0.1

In [ ]:
#Storing rewards after each episode in a list
rewards_per_episode = list()

10000 -
1. - R1
2. - R2
3.  - R3

#Training

In [ ]:
#Greedy Policy
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q_table[state, :])
    return action

In [ ]:
#we iterate over episodes
for e in range(n_episodes): #Entering in the episode
  #we initialize the first state of the episode
  state = env.reset()[0]
  done = False
  action1=choose_action(state)
  #sum the rewards that the agent gets from the environment
  total_reward = 0

  for i in range(steps_allowed): #individual steps taken within an episode
    # epsilon greedy strategy
    # we initiate a random number between 0 and 1
    # if the random_number is less than the exploration proba(epsilon)
    #     the agent explores
    # else
    #     he exploits his knowledge



    # The environment runs the chosen action and returns
    # the next state, a reward and true if the episode is ended.
    next_state, reward, done, truncated , info = env.step(action1)
    action2=choose_action(next_state)

    # We update our Q-table using the Q-learning iteration
    Q_table[state, action1] = (1-lr) * Q_table[state, action1]+ lr*(reward + gamma*(Q_table[next_state,action2]))
    total_reward = total_reward + reward

    state = next_state
    action1=action2
    # If the episode is finished, we leave the for loop
    if done:
        break

  #We update the exploration proba using exponential decay formula
  epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate*e)
  rewards_per_episode.append(total_reward)

In [ ]:
len(rewards_per_episode)

50000

In [ ]:
rewards_per_thousand_episodes=np.split(np.array(rewards_per_episode),50)

In [ ]:
count=1000
print('-----Average reward per thousand episodes-------')
for r in rewards_per_thousand_episodes:
  print(count,':' ,str(sum(r/1000)))
  count+=1000

-----Average reward per thousand episodes-------
1000 : -1133.6600000000017
2000 : -517.5229999999992
3000 : -502.7719999999998
4000 : -501.5839999999999
5000 : -500.792
6000 : -500.396
7000 : -500.0
8000 : -500.198
9000 : -500.099
10000 : -500.59399999999994
11000 : -500.29699999999997
12000 : -500.39599999999996
13000 : -500.099
14000 : -500.099
15000 : -500.0
16000 : -500.198
17000 : -500.099
18000 : -500.198
19000 : -500.39599999999996
20000 : -500.198
21000 : -500.198
22000 : -500.198
23000 : -500.39599999999996
24000 : -500.693
25000 : -500.198
26000 : -500.099
27000 : -500.198
28000 : -500.495
29000 : -500.099
30000 : -500.8909999999999
31000 : -500.39599999999996
32000 : -500.198
33000 : -500.099
34000 : -500.39599999999996
35000 : -500.198
36000 : -500.29699999999997
37000 : -500.49499999999995
38000 : -500.39599999999996
39000 : -500.099
40000 : -500.29699999999997
41000 : -500.198
42000 : -500.198
43000 : -500.099
44000 : -500.29699999999997
45000 : -500.198
46000 : -500.296

In [ ]:
print('-----------Updated Q Table-----------')
print(Q_table)

-----------Updated Q Table-----------
[[ -33.33333436  -33.33333845  -33.33333603  -33.33333388]
 [ -33.33353983  -33.33447375  -33.33338371  -33.33333536]
 [ -33.40370306  -33.80272987  -33.50809409  -33.33333969]
 [ -35.95381786  -37.3480845   -41.23603262  -33.38884672]
 [ -49.81706786  -58.80795236  -61.50167152  -34.58646241]
 [ -70.30940357  -72.02605896  -86.9854649   -44.16297038]
 [ -75.35931102  -72.93484324  -92.30014756  -76.05440238]
 [ -72.64093464  -62.46394108  -94.06803729  -79.62017389]
 [ -66.19175527  -54.54594871  -77.26858704  -72.19714375]
 [ -57.20133999  -51.1003791   -63.84519664  -61.46793858]
 [ -53.16637567  -45.82825094  -53.97761422  -55.86483746]
 [ -51.06649808  -50.63281614  -34.2308021   -51.88975667]
 [ -33.33333429  -33.33343934  -33.33353346  -33.33336391]
 [ -33.33333613  -33.565589    -33.71226562  -33.34218467]
 [ -33.34567174  -39.8135517   -38.48605576  -33.97924719]
 [ -34.18790542  -52.72474654  -76.43097051  -36.49398534]
 [ -44.31178251  -

In [ ]:
import time
from IPython.display import clear_output

In [ ]:
#For recording video
%pip install gymnasium[classic_control] comet_ml
import comet_ml
comet_ml.init(project_name="cliff_walking_q_learning")
env = gym.wrappers.RecordVideo(env, 'gameplay video') #fdiox3CS3j2WHY7yzjJclVgbt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.3/687.3 kB 18.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 979.1/979.1 kB 37.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 53.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 19.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.9/137.9 kB 8.4 MB/s eta 0:00:00
  Attempting uninstall: python-box
    Found existing installation: python-box 7.2.0
    Uninstalling python-box-7.2.0:
      Successfully uninstalled python-box-7.2.0


COMET WARNING: comet_ml.init() is deprecated and will be removed soon. Please use comet_ml.login()


Please paste your Comet API key from https://www.comet.com/api/my/settings/
(api key may not show as you type)


In [ ]:
#Visualising the game
for episode in range(3):
  state=env.reset()[0]
  done=False
  print('----------EPISODE:',episode+1,'---------\n\n\n\n')
  time.sleep(1)

  for step in range(steps_allowed):
    clear_output(wait=True)
    print(env.render())
    time.sleep(0.3)

    action = np.argmax(Q_table[state,:])
    new_state, reward, done, truncated, info = env.step(action)

    if done:
      clear_output(wait=True)
      print(env.render())
      if reward == -100:
          print("****You fell off the cliff****")
          time.sleep(3)
      else:
          print("****You reached the goal****")
          time.sleep(3)
      clear_output(wait=True)
      break

    state=new_state

env.close()